# -*- coding: utf-8 -*-
"""Artwork.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xaV6x2LsXyENIm9ZIAWO473QvGh7TIYr
"""

# This is class Artwork
class Artwork:
  #i have made constructor of Artwork class
    def __init__(self, title, artist, date_of_creation, historical_significance, exhibition_location):
        # i have Initialize attributes
        self.title = title  # Title of the artwork
        self.artist = artist  # Artist of the artwork
        self.date_of_creation = date_of_creation  # Date of creation of the artwork
        self.historical_significance = historical_significance  # Historical significance of the artwork
        self.exhibition_location = exhibition_location  # Location where the artwork being conducted

    # i have made method to get title of the artwork
    def get_title(self):
        return self.title

     # i have made method to get artist of the artwork
    def get_artist(self):
        return self.artist

    # i have made method to get the date of creation of the artwork
    def get_date_of_creation(self):
        return self.date_of_creation

     # i have made method to get the  historical significance of the artwork
    def get_historical_significance(self):
        return self.historical_significance

      # i have made method to get the exhibition location of the artwork
    def get_exhibition_location(self):
        return self.exhibition_location


    def set_title(self, title):
        # i have made method to Set the title of the artwork
        self.title = title

    def set_artist(self, artist):
         # i have made method to Set the artist of the artwork
        self.artist = artist

    def set_date_of_creation(self, date_of_creation):
         # i have made method to Set the date of creation of the artwork
        self.date_of_creation = date_of_creation

    def set_historical_significance(self, historical_significance):
         # i have made method to Set the historical significance of the artwork
        self.historical_significance = historical_significance

    def set_exhibition_location(self, exhibition_location):
         # i have made method to Set the exhibition location of the artwork
        self.exhibition_location = exhibition_location