# -*- coding: utf-8 -*-
"""EducationalProgram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13vfubfKgdLgS0rTGQ1fNNrNfz4udQ2He
"""

# This is class EducationalProgram
class EducationalProgram:
  #i have made constructor of class EducationalProgram
    def __init__(self, program_id, title, duration, time, fee, max_capacity):
    # i have Initialize attributes
        self.program_id = program_id  # ID of the program
        self.title = title  # Title of the program
        self.duration = duration  # Duration of the program in minutes
        self.time = time  # Scheduled time of the program (datetime object)
        self.fee = fee  # Fee for attending the program
        self.max_capacity = max_capacity  # Maximum capacity of participants

   # i have made method to get the ID of the program
    def get_program_id(self):
        return self.program_id

    # i have made method to get the title of the program
    def get_title(self):
        return self.title

    # i have made method to get the duration of the program
    def get_duration(self):
        return self.duration

     # i have made method to get the scheduled time of the program
    def get_time(self):
        return self.time

     # i have made method to get the fee for attending the program
    def get_fee(self):
        return self.fee

     # i have made method to get the maximum capacity of participants for the program
    def get_max_capacity(self):
        return self.max_capacity

    # i have made method to Set the ID of the program
    def set_program_id(self, program_id):
        self.program_id = program_id

     # i have made method to Set the title of the program
    def set_title(self, title):
        self.title = title

     # i have made method to Set the duration of the program
    def set_duration(self, duration):
        self.duration = duration

     # i have made method to Set the scheduled time of the program
    def set_time(self, time):
        self.time = time

     # i have made method to Set the fee for attending the program
    def set_fee(self, fee):
        self.fee = fee

     # i have made method to Set the maximum capacity of participants for the program
    def set_max_capacity(self, max_capacity):
        self.max_capacity = max_capacity