# -*- coding: utf-8 -*-
"""Guide.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CthcJADeBjuvC2TrY7Gqv7wl88r_kLsf
"""

# This is class Guide
class Guide:
  #i have made constructor of class Guide
    def __init__(self, guide_name, guide_id, availability_schedule):
       # i have Initialize attributes
        self.guide_name = guide_name  # Name of the guide
        self.guide_id = guide_id  # ID of the guide
        self.availability_schedule = availability_schedule  # Availability schedule of the guide

   # i have made method to get the name of the guide
    def get_guide_name(self):
        return self.guide_name

    # i have made method to get the ID of the guide
    def get_guide_id(self):
        return self.guide_id

     # i have made method to get the availability schedule of the guide
    def get_availability_schedule(self):
        return self.availability_schedule

 # i have made method to Set the name of the guide
    def set_guide_name(self, guide_name):
        self.guide_name = guide_name

     # i have made method to Set the ID of the guide
    def set_guide_id(self, guide_id):
        self.guide_id = guide_id

     # i have made method to Set the availability schedule of the guide
    def set_availability_schedule(self, availability_schedule):
        self.availability_schedule = availability_schedule