# -*- coding: utf-8 -*-
"""Location.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fv2I38Sa0gNjwfwkOq8uxbzkl51CY8y-
"""

# This is class Location
class Location:
   #i have made constructor of class Location
    def __init__(self, location_name, location_id, location_availability):
         # i have Initialize attributes
        self.location_name = location_name  # Name of the location
        self.location_id = location_id  # ID of the location
        self.location_availability = location_availability  # Availability status of the location

 # i have made method to get the name of the location
    def get_location_name(self):
        return self.location_name

    # i have made method to get the ID of the location
    def get_location_id(self):
        return self.location_id

    def get_location_availability(self):
        # i have made method to get the availability status of the location
        return self.location_availability

# i have made method to set the name of the location
    def set_location_name(self, location_name):
        self.location_name = location_name

 # i have made method to set the ID of the location
    def set_location_id(self, location_id):
        self.location_id = location_id

     # i have made method to set the availability status of the location
    def set_location_availability(self, location_availability):
        self.location_availability = location_availability