# -*- coding: utf-8 -*-
"""SpecialEvents.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jhycuf0SPJ84teg8mUkkzdhgAWBYc6Gj
"""

# This is class SpecialEvents
class SpecialEvents:
  #i have made constructor of SpecialEvents class
    def __init__(self, title, duration, location):
       # i have Initialize attributes
        self.title = title  # Title of the special event
        self.duration = duration  # Duration of the special event (datetime object)
        self.location = location  # Location where the special event takes place

    # i have made method to get title of the special event
    def get_title(self):
        return self.title

     # i have made method to get the duration of the special event
    def get_duration(self):
        return self.duration

     # i have made method to get the location of the special event
    def get_location(self):
        return self.location

  # i have made method to Set the title of the special event
    def set_title(self, title):
        self.title = title

   # i have made method to Set the duration of the special event
    def set_duration(self, duration):
        self.duration = duration