# -*- coding: utf-8 -*-
"""Ticket.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19YxlC8sX_zWP9XALG0_AtUqQtlvzceQl
"""

# This is class Ticket
class Ticket:
   #i have made constructor of class Ticket
    def __init__(self, ticket_id, price, visitor):
       # i have Initialize attributes
        self.ticket_id = ticket_id  # ID of the ticket
        self.price = price  # Price of the ticket
        self.visitor = visitor  # Visitor associated with the ticket

    # i have made method to get the ID of the ticket
    def get_ticket_id(self):
        return self.ticket_id

     # i have made method to get the price of the ticket
    def get_price(self):
        return self.price

  # i have made method to get the ID of the ticket
    def set_ticket_id(self, ticket_id):
        self.ticket_id = ticket_id

    # i have made method to Set the price of the ticket
    def set_price(self, price):
        self.price = price

       # i have made Method to calculate the final price of the ticket
    def calculate_final_price(self):
        # VAT is 5%
        vat = 0.05
        # Calculate final price including VAT
        final_price = self.price * (1 + vat)
        return final_price