# -*- coding: utf-8 -*-
"""TourGuide.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19o35NYjh1Q2TvdjBt4h66P-vgeM3upjz
"""

# This is class TourGuide
class TourGuide:
   #i have made constructor of class TourGuide
    def __init__(self, date, total_visitors, guide):
        # i have Initialize attributes
        self.date = date  # Date of the tour
        self.total_visitors = total_visitors  # Total number of visitors on the tour
        self.guide = guide  # Guide leading the tour

    # i have made method to get the date of the tour
    def get_date(self):
        return self.date

    # i have made method to get the total number of visitors on the tour
    def get_total_visitors(self):
        return self.total_visitors

    # i have made method to get the guide leading the tour
    def get_guide(self):
        return self.guide

  # i have made method to set the date of the tour
    def set_date(self, date):
        self.date = date

    # i have made method to Set the total number of visitors on the tour
    def set_total_visitors(self, total_visitors):
        self.total_visitors = total_visitors

      # i have made method to Set the guide leading the tour
    def set_guide(self, guide):
        self.guide = guide